use-conda: True 
cluster: "sbatch --parsable -p {resources.partitions} {resources.gpu_cmd} --ntasks 1 --cpus-per-task {threads} --mem {resources.mem_mb} --time {resources.runtime}"
cluster-cancel: scancel
default-resources: 
  - partitions="akundaje,owners"
  - runtime="2:00:00"
  - mem_mb=1000
  - gpu_cmd=""

jobs: 100
rerun-triggers: mtime
