workdir: .

max_threads_per_rule: 1

import_dir: /oak/stanford/groups/akundaje/atwang/gp_mouse_chrombpnet_import
export_dir: /oak/stanford/groups/akundaje/atwang/gp_mouse_chrombpnet_results

folds_used:
  - 0
  - 1
  - 2
  - 3
  - 4

abc_slop: 5000000
abc_gamma: 0.87